<!DOCTYPE html>
<html lang="id" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'App') - {{ config('app.name', 'Laravel') }}</title>
    
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    
    @stack('styles')
</head>
<body class="bg-base-200 min-h-screen flex flex-col">
    <!-- Navbar -->
    <nav class="navbar bg-base-100 shadow-lg sticky top-0 z-50">
        <div class="navbar-start">
            <!-- Mobile Menu -->
            <div class="dropdown">
                <label tabindex="0" class="btn btn-ghost lg:hidden">
                    <span class="icon-[tabler--menu-2] size-6"></span>
                </label>
                <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                    <li><a href="{{ url('/') }}"><span class="icon-[tabler--home]"></span> Home</a></li>
                    @yield('mobile-menu')
                </ul>
            </div>
            <a class="btn btn-ghost text-xl font-bold" href="{{ url('/') }}">
                <span class="icon-[tabler--box] size-6 text-primary"></span>
                {{ config('app.name', 'Laravel App') }}
            </a>
        </div>
        
        <!-- Desktop Menu -->
        <div class="navbar-center hidden lg:flex">
            <ul class="menu menu-horizontal px-1 gap-1">
                <li><a href="{{ url('/') }}" class="btn btn-ghost btn-sm">
                    <span class="icon-[tabler--home]"></span> Home
                </a></li>
                @yield('navbar-menu')
            </ul>
        </div>
        
        <!-- Right Side -->
        <div class="navbar-end gap-2">
            <!-- Theme Toggle -->
            <label class="swap swap-rotate btn btn-ghost btn-circle">
                <input type="checkbox" class="theme-controller" value="dark" />
                <span class="swap-off icon-[tabler--sun] size-5"></span>
                <span class="swap-on icon-[tabler--moon] size-5"></span>
            </label>
            
            @guest
                @if (Route::has('login'))
                    <a href="{{ route('login') }}" class="btn btn-primary btn-sm">
                        <span class="icon-[tabler--login]"></span> Login
                    </a>
                @endif
            @else
                <div class="dropdown dropdown-end">
                    <label tabindex="0" class="btn btn-ghost btn-circle avatar placeholder">
                        <div class="bg-primary text-primary-content rounded-full w-10">
                            <span class="text-lg">{{ substr(Auth::user()->name, 0, 1) }}</span>
                        </div>
                    </label>
                    <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                        <li class="menu-title">{{ Auth::user()->name }}</li>
                        <li>
                            <a href="{{ route('logout') }}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <span class="icon-[tabler--logout]"></span> Logout
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </div>
            @endguest
        </div>
    </nav>

    <!-- Main Content -->
    <main class="flex-1 py-6">
        <div class="container mx-auto px-4">
            @yield('content')
        </div>
    </main>

    <!-- Footer -->
    <footer class="footer footer-center p-4 bg-base-100 text-base-content border-t">
        <aside>
            <p class="flex items-center gap-2">
                <span class="icon-[tabler--code] size-4"></span>
                &copy; {{ date('Y') }} {{ config('app.name', 'Laravel') }} - 
                Generated by <a href="http://harviacode.com" target="_blank" class="link link-primary">Harviacode CRUD Generator</a>
            </p>
        </aside>
    </footer>

    @stack('scripts')
</body>
</html>