<?php

/**
 * Laravel Model Generator
 * Generates Eloquent Model for Laravel
 */

// Convert table name to Model name (singular, PascalCase)
function tableToModelName($table_name)
{
    $words = explode('_', $table_name);
    $model_name = '';
    foreach ($words as $word) {
        $model_name .= ucfirst(strtolower($word));
    }
    // Simple singularization
    if (substr($model_name, -1) === 's') {
        $model_name = rtrim($model_name, 's');
    }
    return $model_name;
}

$model_name = isset($custom_model) && $custom_model != '' ? $custom_model : tableToModelName($table_name);

$string = "<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class " . $model_name . " extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected \$table = '$table_name';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected \$primaryKey = '$pk';
";

// Add timestamps handling
$has_created_at = false;
$has_updated_at = false;
foreach ($all as $row) {
    if ($row['column_name'] === 'created_at')
        $has_created_at = true;
    if ($row['column_name'] === 'updated_at')
        $has_updated_at = true;
}

if (!$has_created_at || !$has_updated_at) {
    $string .= "
    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public \$timestamps = false;
";
}

// Fillable fields
$string .= "
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected \$fillable = [";

foreach ($non_pk as $row) {
    $string .= "\n        '" . $row['column_name'] . "',";
}

$string .= "
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected \$casts = [";

foreach ($all as $row) {
    $type = strtolower($row['data_type']);
    $cast_type = null;

    if (in_array($type, ['int', 'integer', 'bigint', 'smallint', 'tinyint'])) {
        $cast_type = 'integer';
    } elseif (in_array($type, ['decimal', 'float', 'double'])) {
        $cast_type = 'float';
    } elseif (in_array($type, ['boolean', 'bool'])) {
        $cast_type = 'boolean';
    } elseif ($type === 'datetime' || $type === 'timestamp') {
        $cast_type = 'datetime';
    } elseif ($type === 'date') {
        $cast_type = 'date';
    } elseif ($type === 'json') {
        $cast_type = 'array';
    }

    if ($cast_type && $row['column_name'] !== $pk) {
        $string .= "\n        '" . $row['column_name'] . "' => '" . $cast_type . "',";
    }
}

$string .= "
    ];
}

/* End of file " . $model_name . ".php */
/* Location: ./app/Models/" . $model_name . ".php */
/* Generated by Harviacode CRUD Generator " . date('Y-m-d H:i:s') . " */
/* http://harviacode.com */
";

// Create file
$model_file = $model_name . '.php';
$hasil_laravel_model = createFile($string, $target . $model_file);

?>