<?php

/**
 * Laravel Migration Generator
 * Generates Database Migration for Laravel
 */

$migration_class = 'Create' . str_replace(' ', '', ucwords(str_replace('_', ' ', $table_name))) . 'Table';

$string = "<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('$table_name', function (Blueprint \$table) {";

foreach ($all as $row) {
    $col = $row['column_name'];
    $type = strtolower($row['data_type']);
    $is_pk = ($col === $pk);
    $nullable = (isset($row['is_nullable']) && $row['is_nullable'] === 'YES') ? '->nullable()' : '';

    // Map MySQL types to Laravel Schema types
    if ($is_pk) {
        if ($type === 'int' || $type === 'integer' || $type === 'bigint') {
            $string .= "\n            \$table->id('$col');";
        } else {
            $string .= "\n            \$table->string('$col')->primary();";
        }
    } elseif (in_array($type, ['int', 'integer'])) {
        $string .= "\n            \$table->integer('$col')$nullable;";
    } elseif ($type === 'bigint') {
        $string .= "\n            \$table->bigInteger('$col')$nullable;";
    } elseif ($type === 'smallint') {
        $string .= "\n            \$table->smallInteger('$col')$nullable;";
    } elseif ($type === 'tinyint') {
        // Check if it's boolean (tinyint(1))
        $column_type = isset($row['column_type']) ? $row['column_type'] : '';
        if ($column_type && strpos($column_type, '(1)') !== false) {
            $string .= "\n            \$table->boolean('$col')$nullable->default(false);";
        } else {
            $string .= "\n            \$table->tinyInteger('$col')$nullable;";
        }
    } elseif (in_array($type, ['decimal', 'numeric'])) {
        $precision = isset($row['numeric_precision']) ? $row['numeric_precision'] : 10;
        $scale = isset($row['numeric_scale']) ? $row['numeric_scale'] : 2;
        $string .= "\n            \$table->decimal('$col', $precision, $scale)$nullable;";
    } elseif ($type === 'float') {
        $string .= "\n            \$table->float('$col')$nullable;";
    } elseif ($type === 'double') {
        $string .= "\n            \$table->double('$col')$nullable;";
    } elseif (in_array($type, ['varchar', 'char'])) {
        $length = isset($row['character_maximum_length']) ? $row['character_maximum_length'] : 255;
        if ($length > 255)
            $length = 255;
        $string .= "\n            \$table->string('$col', $length)$nullable;";
    } elseif ($type === 'text') {
        $string .= "\n            \$table->text('$col')$nullable;";
    } elseif ($type === 'mediumtext') {
        $string .= "\n            \$table->mediumText('$col')$nullable;";
    } elseif ($type === 'longtext') {
        $string .= "\n            \$table->longText('$col')$nullable;";
    } elseif ($type === 'date') {
        $string .= "\n            \$table->date('$col')$nullable;";
    } elseif ($type === 'datetime') {
        $string .= "\n            \$table->dateTime('$col')$nullable;";
    } elseif ($type === 'timestamp') {
        if ($col === 'created_at' || $col === 'updated_at') {
            // Skip, will add timestamps() later
        } else {
            $string .= "\n            \$table->timestamp('$col')$nullable;";
        }
    } elseif ($type === 'time') {
        $string .= "\n            \$table->time('$col')$nullable;";
    } elseif ($type === 'year') {
        $string .= "\n            \$table->year('$col')$nullable;";
    } elseif ($type === 'json') {
        $string .= "\n            \$table->json('$col')$nullable;";
    } elseif (in_array($type, ['blob', 'binary'])) {
        $string .= "\n            \$table->binary('$col')$nullable;";
    } elseif (strpos($type, 'enum') !== false) {
        // Try to extract enum values
        $string .= "\n            \$table->string('$col')$nullable; // TODO: Convert to enum if needed";
    } else {
        // Default to string
        $string .= "\n            \$table->string('$col')$nullable;";
    }
}

// Check if we need to add timestamps
$has_created_at = false;
$has_updated_at = false;
foreach ($all as $row) {
    if ($row['column_name'] === 'created_at')
        $has_created_at = true;
    if ($row['column_name'] === 'updated_at')
        $has_updated_at = true;
}

if ($has_created_at && $has_updated_at) {
    $string .= "\n            \$table->timestamps();";
}

$string .= "
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('$table_name');
    }
};

/* Generated by Harviacode CRUD Generator " . date('Y-m-d H:i:s') . " */
/* http://harviacode.com */
";

// Create file with timestamp
$migration_file = date('Y_m_d_His') . '_create_' . $table_name . '_table.php';
$hasil_laravel_migration = createFile($string, $target . $migration_file);

?>