<?php

/**
 * Laravel Routes Generator
 * Generates Route definitions for Laravel
 */

$model_name = isset($custom_model) && $custom_model != '' ? $custom_model : tableToModelName($table_name);
$controller_name = $model_name . 'Controller';
$route_name = strtolower($table_name);

$string = "<?php

/**
 * Routes for $model_name
 * Add this to your routes/web.php file
 */

use App\Http\Controllers\\" . $controller_name . ";

// Resource routes for $model_name
Route::resource('$route_name', " . $controller_name . "::class);
";

// Export routes
if ($export_excel == '1' || $export_word == '1') {
    $string .= "
// Export routes";
}

if ($export_excel == '1') {
    $string .= "
Route::get('$route_name/export/excel', [" . $controller_name . "::class, 'exportExcel'])->name('$route_name.export.excel');";
}

if ($export_word == '1') {
    $string .= "
Route::get('$route_name/export/word', [" . $controller_name . "::class, 'exportWord'])->name('$route_name.export.word');";
}

$string .= "

/**
 * Available routes:
 * 
 * GET    /$route_name              - index   - Display listing
 * GET    /$route_name/create       - create  - Show create form
 * POST   /$route_name              - store   - Store new record
 * GET    /$route_name/{id}         - show    - Display specific record
 * GET    /$route_name/{id}/edit    - edit    - Show edit form
 * PUT    /$route_name/{id}         - update  - Update specific record
 * DELETE /$route_name/{id}         - destroy - Delete specific record
 */

/* Generated by Harviacode CRUD Generator " . date('Y-m-d H:i:s') . " */
/* http://harviacode.com */
";

// Create file
$route_file = $route_name . '_routes.php';
$hasil_laravel_routes = createFile($string, $target . $route_file);

?>