<?php

/**
 * Laravel Form Request Generator
 * Generates Form Request Validation for Laravel
 */

$model_name = isset($custom_model) && $custom_model != '' ? $custom_model : tableToModelName($table_name);
$request_name = $model_name . 'Request';

$string = "<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class " . $request_name . " extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [";

foreach ($non_pk as $row) {
    $rules = [];

    // Required rule
    if (isset($row['is_nullable']) && $row['is_nullable'] === 'NO') {
        $rules[] = 'required';
    } else {
        $rules[] = 'nullable';
    }

    // Type-based rules
    $type = strtolower($row['data_type']);
    if (in_array($type, ['int', 'integer', 'bigint', 'smallint', 'tinyint'])) {
        $rules[] = 'integer';
    } elseif (in_array($type, ['decimal', 'float', 'double'])) {
        $rules[] = 'numeric';
    } elseif (in_array($type, ['varchar', 'char', 'text'])) {
        $rules[] = 'string';
        if (isset($row['character_maximum_length']) && $row['character_maximum_length'] > 0) {
            $rules[] = 'max:' . $row['character_maximum_length'];
        }
    } elseif ($type === 'date') {
        $rules[] = 'date';
    } elseif ($type === 'datetime' || $type === 'timestamp') {
        $rules[] = 'date';
    } elseif ($type === 'email') {
        $rules[] = 'email';
    }

    // Check for email in column name
    if (stripos($row['column_name'], 'email') !== false) {
        $rules[] = 'email';
    }

    $rules_string = implode('|', $rules);
    $string .= "\n            '" . $row['column_name'] . "' => '" . $rules_string . "',";
}

$string .= "
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return [";

foreach ($non_pk as $row) {
    $label = label($row['column_name']);
    $string .= "\n            '" . $row['column_name'] . "' => '" . $label . "',";
}

$string .= "
        ];
    }

    /**
     * Get the error messages for the defined validation rules.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'required' => ':attribute wajib diisi.',
            'string' => ':attribute harus berupa teks.',
            'integer' => ':attribute harus berupa angka.',
            'numeric' => ':attribute harus berupa angka.',
            'email' => ':attribute harus berupa alamat email yang valid.',
            'date' => ':attribute harus berupa tanggal yang valid.',
            'max' => ':attribute tidak boleh lebih dari :max karakter.',
        ];
    }
}

/* End of file " . $request_name . ".php */
/* Location: ./app/Http/Requests/" . $request_name . ".php */
/* Generated by Harviacode CRUD Generator " . date('Y-m-d H:i:s') . " */
/* http://harviacode.com */
";

// Create file
$request_file = $request_name . '.php';
$hasil_laravel_request = createFile($string, $target . $request_file);

?>